### ISSUE TITLE
Unable to run MOD on Sinytra Connector

### ISSUE THREAD

**Issue by wc7086** [sakura-ryoko/servux#12]
log
https://mclo.gs/JLzZ5sw

**Comment by sakura-ryoko** [comment]
You are trying to use a Fabric Mod with Forge; that is your issue.
```
22Sep2024 20:39:21.067] [main/WARN] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Skipping jar. File /mnt/data/minecraft/mods/servux-fabric-1.21-0.3.8-sakura.1.jar is a Fabric mod and cannot be loaded
```

**Comment by sakura-ryoko** [comment]
SEE: https://github.com/ThinkingStudios/Servux-Forge/tree/neoforge/1.21.1/dev
Forge port.

**Comment by wc7086** [comment]
> You are trying to use a Fabric Mod with Forge; that is your issue.

Apologies for the lack of information, the “Sinytra Connector” I was referring to is a compatibility layer that allows most Fabric Mods to run on Foerge. Adapting to that compatibility layer may require some knowledge of it, but I don't know much about it.

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
