### ISSUE TITLE
[Question] Stackable shulker boxes on servers?

### ISSUE THREAD

**Issue by ARedstoneMan** [sakura-ryoko/servux#5]
So due to the new item stacking component changes in 1.21, you can now create 64-stackable shulkers with one vanilla command. However, there is a major issue with this, that being these shulker boxes will now constantly be treated as 64-stackable items, even while transferred through hoppers or read with comparators (basically while in any inventory, not just the player's). This is a problem because now, significantly more buffer shulker boxes are needed to entirely prefill something like a collection system.

Why is this significant? Well, when using the stackable shulker boxes rule from carpet or tweakeroo and paired with essential client's shulker box stacking in player inventories rule, they behave almost exactly as they would if they were used in <1.21
but ONLY in SINGLEPLAYER.
Outside of singleplayer, they behave as 64 stackables always.

Why is this the case? And is it possible to add serverside support to revert the stackable shulker box behavior as in previous versions or at least make them not stack in inventories like chests or hoppers?

**Comment by Ka1nnn** [comment]
You can use this mod by kiku to prevent them from stacking in hoppers. 

https://modrinth.com/mod/stackable-shulkers-fix

Although personally I don't see the point anymore in using stacked boxes at least for farms or storages where you can just simply add a box crafter and ur done.

**Comment by sakura-ryoko** [comment]
The mod link posted above I believe is your solution.
The reason is due to Vanilla changes in how the game Calculates the `ItemStack.getMaxCount()` function using Data Components.
