### ISSUE TITLE
Log spam when a player doesn't have permissions

### ISSUE THREAD

**Issue by Syntaxvgm** [sakura-ryoko/servux#7]
![servux](https://github.com/user-attachments/assets/d64a10a5-bc1f-45c0-9570-ff8b3fe9c617)
![servux2](https://github.com/user-attachments/assets/31a97329-f876-47fa-a1d0-1fd625500dec)

In all seriousness having it spam the console several times a second for ever player with litematica who doesn't have permission makes the option of not providing permissions a bit unusable unless you use a log spam cleaning mod with it. Perhaps move this one to debug level?

**Comment by sakura-ryoko** [comment]
It wasn't really a tested feature yet.

**Comment by sakura-ryoko** [comment]
Please try 0.3.4 --> https://github.com/sakura-ryoko/servux/releases/tag/1.21-0.3.4
